---
title: "<center>Publications</center>"
output: 
  html_document:
    css: "style.css"
---

# {.tabset}

## *Journal articles (peer-reviewed)*

### **2021**

**Kattner, F.** (2021). Transfer of working memory training to the inhibitory control of auditory distraction. *Psychological Research*. doi: 10.1007/s00426-020-01468-0

### **2020**

Dale, G., **Kattner, F.**, Bavelier, D., & Green, C. S. (2020). Cognitive abilities of action-videogame and role-playing videogame players: Data from a Massive Open Online Course. *Psychology of Popular Media Culture, 9*(3), 347–358. doi: [10.1037/ppm0000237](https://psycnet.apa.org/record/2019-23599-001)

Ellermeier, W., **Kattner, F.**, Klippenstein, E., Kreis, M., & Marquis-Favre, C. (2020). Short-term noise annoyance and electrodermal response as a function of sound-pressure level, cognitive task load, and noise sensitivity. *Noise and Health, 22*(105), 46-55. doi: [10.4103/nah.NAH_47_19](https://www.noiseandhealth.org/text.asp?2020/22/105/46/304702)

**Kattner, F.**^+^ & Clausen, A.^+^ (2020). Revisiting the prioritization of emotional information in iconic memory. *Royal Society Open Science, 7*, 191507. doi. [10.1098/rsos.191507](https://dx.doi.org/10.1098/rsos.191507)

**Kattner, F.** & Ellermeier, W. (2020). Distraction at the cocktail party: Attenuation of the irrelevant speech effect after a training of auditory selective attention. *Journal of Experimental Psychology: Human Perception and Performance, 46*(1), 10-20. doi: [10.1037/xhp0000695](http://dx.doi.org/10.1037/xhp0000695)

**Kattner, F.** & Meinhardt, H. (2020). Dissociating the disruptive effects of irrelevant music and speech on serial recall of tonal and verbal sequences. *Frontiers in Psychology, 11*, 346. doi: [10.3389/fpsyg.2020.00346](https://www.frontiersin.org/articles/10.3389/fpsyg.2020.00346/full)

**Kattner, F.**^+^ & Reimer, C.^+^ (2020). Dissociating central and auditory attention: Is there a shared bottleneck for response selection and auditory search? *Quarterly Journal of Experimental Psychology, 73*(10), 1564-1574. doi: [10.1177/1747021820928030](https://journals.sagepub.com/eprint/6PFECTH2HXAKXKVIV9HF/full)

### **2019**

**Kattner, F.** & Green, C. S. (2019). Enhanced early visual processing after evaluative conditioning. *Acta Psychologica, 197*, 1-9. doi: [10.1016/j.actpsy.2019.04.009](https://www.ncbi.nlm.nih.gov/pubmed/31030084)

**Kattner, F.**, Samaan, L., & Schubert, T. (2019). Cross-modal transfer after auditory task-switching training. *Memory & Cognition, 47*(5), 1044-1061. doi: [10.3758/s13421-019-00911-x](https://link.springer.com/article/10.3758%2Fs13421-019-00911-x)

Stiller, A.-K., **Kattner, F.**, Gunzenhauser, C., & Schmitz, B. (2019). The effect of positive reappraisal on the availability of self-control resources and self-regulated learning. *Educational Psychology, 39*(1), 86-111. doi: [10.1080/01443410.2018.1524851](https://www.tandfonline.com/doi/abs/10.1080/01443410.2018.1524851?journalCode=cedp20)

Ueda, K., Nakajima, Y., **Kattner, F.**, & Ellermeier, W. (2019). Irrelevant speech effects with locally time-reversed speech: Native vs non-native language. *Journal of the Acoustical Society of America, 145*, 3686-3694. doi: [10.1121/1.5112774](https://www.kog.psychologie.tu-darmstadt.de/media/angewandtekognitionspsychologie/pubs/Ueda_Nakaj_Kattn_Ell_JASA_2019.pdf)

### **2018**

**Kattner, F.** & Ellermeier, W. (2018). Emotional prosody of task-irrelevant speech interferes with the retention of serial order. *Journal of Experimental Psychology: Human Perception and Performance, 44*(8), 1303-1312. doi: [10.1037/xhp0000537](http://psycnet.apa.org/record/2018-14658-001)

### **2017**

Green, C. S., **Kattner, F.**, Eichenbaum, A., Bediou, B., Adams, D., Mayer, R., & Bavelier, D. (2017). Playing some video games but not others is related to cognitive abilities – a critique of Unsworth et al. (2015). *Psychological Science, 28*(5), 679-682. doi: [10.1177/0956797616644837](http://journals.sagepub.com/doi/abs/10.1177/0956797616644837)

**Kattner, F.**, Cochrane, A., & Green, C. S. (2017). Trial-dependent psychometric functions accounting for perceptual learning in 2-AFC discrimination tasks. *Journal of Vision, 17*(11), 3. doi: [10.1167/17.11.3](http://jov.arvojournals.org/article.aspx?articleid=2653463)

**Kattner, F.**^+^, Cochrane, A.^+^, Cox, C. R., Gorman, T., & Green, C. S. (2017). Perceptual learning generalization from sequential perceptual training as a change in learning rate. *Current Biology, 27*(6), 840-846. doi: [10.1016/j.cub.2017.01.046](http://www.cell.com/current-biology/fulltext/S0960-9822(17)30081-7)

Ueda, K., Nakajima, Y., Ellermeier, W., & **Kattner, F.** (2017). Intelligibility of locally time-reversed speech: A multilingual comparison. *Scientific Reports, 7*, 1782. doi: [10.1038/s41598-017-01831-z](https://www.nature.com/articles/s41598-017-01831-z.pdf)

### **2016**

Gast, A.^+^ & **Kattner, F.**^+^ (2016). Single-trial evaluative conditioning can be moderated by instructed forgetting. *Learning & Behavior, 44*, 260-269. doi: [10.3758/s13420-016-0210-9](http://link.springer.com/article/10.3758%2Fs13420-016-0210-9)

**Kattner, F.**, Cox, C. R., & Green, C. S. (2016). Transfer in rule-based category learning depends on the training task. *PLoS ONE, 11*(10): e0165260. doi: [10.1371/journal.pone.0165260](http://journals.plos.org/plosone/article/asset?id=10.1371/journal.pone.0165260.PDF)

**Kattner, F.** & Green, C. S. (2016). Transfer of dimensional associability in human contingency learning. *Journal of Experimental Psychology: Animal Learning and Cognition, 42*(1), 15-31. doi: [10.1037/xan0000082](https://www.apa.org/pubs/journals/features/xan-xan0000082.pdf)

### **2015**

Birkenbusch, J., Ellermeier, W., & **Kattner, F.** (2015). Octuplicate this interval! Axiomatic examination of the ratio properties of duration perception. *Attention, Perception, & Psychophysics, 77*, 1767-1780. doi: [10.3758/s13414-015-0846-0](https://link.springer.com/article/10.3758/s13414-015-0846-0)

Ellermeier, W., **Kattner, F.**, Ueda, K., Doumoto, K., & Nakajima, Y. (2015). Memory disruption by irrelevant noise-vocoded speech: Effects of native language and the number of frequency bands. *Journal of the Acoustical Society of America, 138*, 1561-1569. doi: [10.1121/1.4928954](http://scitation.aip.org/content/asa/journal/jasa/138/3/10.1121/1.4928954)

Eichenbaum A., **Kattner F.**, Bradford D., Gentile D. A., Choo, H., Chen, V. H. H., Khoo, A., & Green C. S. (2015). The role of game genres and the development of internet gaming disorder in school-aged children. *Journal of Addictive Behaviors, Therapy & Rehabilitation, 4*(3), 1-7. doi: [10.4172/2324-9005.1000141](https://www.scitechnol.com/peer-review/the-role-of-game-genres-and-the-development-of-internet-gaming-disorder-in-school-aged-children-0Tkd.php?article_id=3900)

Eichenbaum, A.^+^, **Kattner, F.**^+^, Bradford, D., Gentile, D. A., & Green, C. S. (2015). Role-playing and real-time strategy games associated with greater probability of internet gaming disorder. *Cyberpsychology, Behavior, and Social Networking, 18*, 480-485. doi: [10.1089/cyber.2015.0092](https://pubmed.ncbi.nlm.nih.gov/26252934/)

Green, C. S., **Kattner, F.**, Siegel, M. H., Kersten, D., & Schrater, P. R. (2015). Differences in perceptual learning transfer as a function of training task. *Journal of Vision, 15*(10), 5. doi: [10.1167/15.10.5](http://jov.arvojournals.org/article.aspx?articleid=2429948)

**Kattner, F.** (2015). Transfer of absolute and relative predictiveness in human contingency learning. *Learning & Behavior, 43*, 32-43. doi: [10.3758/s13420-014-0159-5](http://link.springer.com/article/10.3758/s13420-014-0159-5)

**Kattner, F.** & Green, C. S. (2015). Cue competition in evaluative conditioning as a function of the learning process. Acta Psychologica, 162, 40-50. doi: [10.1016/j.actpsy.2015.09.013](http://www.sciencedirect.com/science/article/pii/S0001691815300615)

Snell, N., **Kattner, F.**, Rokers, B., & Green, C. S. (2015). Orientation transfer in vernier and stereoacuity training. *PLoS ONE, 10*(12): e0145770. doi: [10.1371/journal.pone.0145770](http://journals.plos.org/plosone/article?id=10.1371%2Fjournal.pone.0145770)

### **2014**

Ellermeier, W., **Kattner, F.**, Kurtze, L., & Bös, J. (2014). Psychoacoustic characterization of the noise produced by photovoltaic inverters. *Acta Acustica united with Acustica, 100*(6), 1120-1128. doi: [10.3813/AAA.918791](https://www.ingentaconnect.com/content/dav/aaua/2014/00000100/00000006/art00014)

**Kattner, F.** (2014). Reconsidering the (in)sensitivity of evaluative conditioning to reinforcement density and CS-US contingency. *Learning and Motivation, 45*, 15-29. doi: [10.1016/j.lmot.2013.09.002](http://www.sciencedirect.com/science/article/pii/S0023969013000349)

**Kattner, F.** & Ellermeier, W. (2014a). Irrelevant speech does not interfere with serial recall in early blind listeners. *Quarterly Journal of Experimental Psychology, 67*(11), 2207-2217. doi: [10.1080/17470218.2014.910537](https://journals.sagepub.com/doi/10.1080/17470218.2014.910537)

**Kattner, F.** & Ellermeier, W. (2014b). Fractionation of pitch intervals: An axiomatic study testing monotonicity, commutativity, and multiplicativity in musicians and non-musicians. *Attention, Perception, & Psychophysics, 76*(8), 2508-2521. doi: [10.3758/s13414-014-0674-7](http://link.springer.com/article/10.3758%2Fs13414-014-0674-7)

### **before 2014**

**Kattner, F.**, Ellermeier, W., & Tavakoli, P. (2012). Both trace and delay conditioning of evaluative responses depend on contingency awareness. *Learning and Motivation, 43*, 35-47. doi: [10.1016/j.lmot.2012.01.004](http://www.sciencedirect.com/science/article/pii/S0023969012000057)

**Kattner, F.** (2012). Revisiting the relation between contingency awareness and attention: Evaluative conditioning relies on a contingency focus. *Cognition and Emotion, 26*(1), 166-175. doi: [10.1080/02699931.2011.565036](http://www.tandfonline.com/doi/full/10.1080/02699931.2011.565036)

Bösche, W. & **Kattner, F.** (2011). Fear of (serious) digital games and game-based learning? *International Journal of Game-Based Learning, 1*(3), 1-15. doi: [10.4018/ijgbl.2011070101](https://www.igi-global.com/article/fear-serious-digital-games-game/56311)

**Kattner, F.** & Ellermeier, W. (2011). Does evaluative learning rely on the perception of contingency? Manipulating contingency and US density during evaluative conditioning. *Experimental Psychology, 58*(5), 391-399. doi: [10.1027/1618-3169/a000108](http://econtent.hogrefe.com/doi/abs/10.1027/1618-3169/a000108?url_ver=Z39.88-2003&rfr_id=ori%3Arid%3Acrossref.org&rfr_dat=cr_pub%3Dpubmed&)

^+^ authors contributed equally


## *Conference proceedings*

### **2020**

Ellermeier, W., **Kattner, F.**, & Le Favre, C. (2020). Role of noise sensitivity in modulating both annoyance ratings and electrodermal
responses to traffic noise. Paper presented at [*Forum Acusticum 2020*](https://fa2020.universite-lyon.fr/), 7-11 December 2020, Lyon, France {Online}.

Ellermeier, W., **Kattner, F.**, & Raum, A. (2020). Cross-modal commutativity of brightness and loudness productions. In J. Schoenherr, T. Hubbard, W. Stine, & C. Leth-Steenson (Eds.). [*Proceedings of the 36th Annual Meeting of the International Society for Psychophysics Fechner Day 2020*](http://fechnerday.com/fd2020/wp-content/uploads/2020/12/FD2020_Full-Proceedngs-160920-V3-compressed.pdf) (p. 17). International Society for Psychophysics {Online}.

**Kattner, F.**, Hanl, S., Paul, L., & Ellermeier, W. (2020). Irrelevant sound effects on mental arithmetic. [*Online Workshop Distraction and Attention*](https://www.dropbox.com/sh/br6qftzog6ptf7q/AAAFiXZ1hRqxoqUQl2hmXVKSa?dl=0), 21 September 2020. University of Central Lancashire.

### **2019**

Clausen, A. & **Kattner, F.** (2019). Revisiting the prioritization of emotional information in iconic memory: A pre-registered replication study. In C. Lange-Küttner (Ed.). [*Annual Meeting of Experimental Psychologists* (TEAP 2019)](https://easychair.org/smart-program/TEAP2019/program.html). London, UK: London Metropolitan University.

K**attner, F.** & Ellermeier, W. (2019). Does training in auditory filtering reduce the irrelevant speech effect on serial recall? In C. Lange-Küttner (Ed.). [*Annual Meeting of Experimental Psychologists* (TEAP 2019)](https://easychair.org/smart-program/TEAP2019/program.html). London, UK: London Metropolitan University.

### **2018**

Ellermeier, W., **Kattner, F.**, Klippenstein, E., & Marquis-Favre, C. (2018). Judging noise annoyance as a function of task load: Effects of noise sensitivity. In F. Müller, L. Ludwigs, & M. Kupper (Eds.), [*Fechner Day 2018: Proceedings of the 34th Annual Meeting of the International Society for Psychophysics*](http://proceedings.fechnerday.com/index.php/proceedings/article/view/616/603) (pp. 72-77), International Society for Psychophysics: Lüneburg, Germany, 20-24 August 2018.

**Kattner, F.**, Coels, S., & Ellermeier, W.. (2018). Perceptual control of the irrelevant speech effect as a result of training on a dichotic listening task. In F. Müller, L. Ludwigs, & M. Kupper (Eds.), [*Fechner Day 2018: Proceedings of the 34th Annual Meeting of the International Society for Psychophysics*](http://proceedings.fechnerday.com/index.php/proceedings/article/view/616/603) (pp. 203-207), International Society for Psychophysics: Lüneburg, Germany, 20-24 August 2018.

### **2017**

**Kattner, F.** (2017). Specificity of perceptual learning in an auditory interval categorization task. In K. Ueda, H. Ito, G. B. Remijn, & Y. Nakajima (Eds.), *Fechner Day 2017: Proceedings of the 33rd Annual Meeting of the International Society of Psychophysics* (pp. 119-124). International Society for Psychophysics, Fukuoka, Japan.

Ellermeier, W., **Kattner, F.**, Ueda, K., & Nakajima, Y. (2017). Irrelevant sound effects with locally time-reversed speech. In K. Ueda, H. Ito, G. B. Remijn, & Y. Nakajima (Eds.), [*Fechner Day 2017: Proceedings of the 33rd Annual Meeting of the International Society of Psychophysics*](http://proceedings.fechnerday.com/index.php/proceedings/article/view/587/575) (pp. 42-47). International Society for Psychophysics, Fukuoka, Japan.

Ellermeier, W., **Kattner, F.**, & Hanl, S. (2017). The irrelevant speech effect is modified by emotional prosody. In T. Goschke, A. Bolte, & C. Kirschbaum (Eds.), [*Abstracts of the 59th Conference of Experimental Psychologists*](https://www.amazon.de/TeaP-2017-Conference-Experimental-Psychologists-ebook/dp/B06XSYWVZ7) (p. 41), 26-29 March 2017, Dresden, Germany.

**Kattner, F.** & Green, C. S. (2017). The impact of evaluative conditioning on early sensory processing. In T. Goschke, A. Bolte, & C. Kirschbaum (Eds.), [*Abstracts of the 59th Conference of Experimental Psychologists*](https://www.amazon.de/TeaP-2017-Conference-Experimental-Psychologists-ebook/dp/B06XSYWVZ7) (p. 161), 26-29 March 2017, Dresden, Germany.

Ueda, K., Shibata, A., Nakajima, Y., Rost, K., **Kattner, F.**, & Ellermeier, W. (2017). Irrelevant sound effects with locally time-reversed speech: Real performance difference between German and Japanese native speakers? In K. Ueda, H. Ito, G. B. Remijn, & Y. Nakajima (Eds.), [*Fechner Day 2017: Proceedings of the 33rd Annual Meeting of the International Society of Psychophysics*](http://proceedings.fechnerday.com/index.php/proceedings/article/view/587/575) (p. 222). International Society for Psychophysics, Fukuoka, Japan.

### **2016**

Ueda, K., Nakajima, Y., Tamura, S., Shichida, A., Ellermeier, W., **Kattner, F.**, Daebler, S., & Nie Neo, N. (2016). Intelligibility of locally time-reversed speech in Chinese, English, German, and Japanese. [*31st International Congress of Psychology*](https://psych.or.jp/icp2016/program08.html). 24-29 July 2016, Yokohama, Japan.

**Kattner, F.** & Green, C. S. (2016). Stimulus specificity of intradimensional and extradimensional transfer effects in associative learning. In J. Funke, J. Rummel, & A. Voss (Eds), [*Abstracts of the 58th Conference of Experimental Psychologists*](https://www.psychologie.uni-heidelberg.de/ae/allg_en/mitarb/jf/Funke%20Rummel%20Voss%202016%20Teap%20abstracts.pdf) (pp. 152-153). 21-23 March 2016, Heidelberg, Germany.

Ueda, K., Nakajima, Y., Ellermeier, W., & **Kattner, F.** (2016). A multilingual comparison of intelligibility in locally time-reversed speech. *Proceedings of the Auditory Research Meeting, 46*(3), 181-186.

### **2015**

Ueda, K., Nakajima, Y., Tamura, S., Ellermeier, W., **Kattner, F.**, & Daebler, S. (2015). The effect of segment duration on the intelligibility of locally time-reversed speech: A multilingual comparison. In S. Grondin \& V. Laflamme (Eds.), [*Proceedings of the 31st Annual Meeting of the International Society for Psychophysics (Fechner Day 2015)*](http://proceedings.fechnerday.com/index.php/proceedings/article/view/584/572) (p. 42), 17-21 August 2015, Quebec City, Canada.

**Kattner, F.**, White, P., & Green, C. S. (2015). Cue competition effects in evaluative conditioning. Paper presented at the *Small Group Meeting Associative and Propositional Learning*, 18-20 June, 2015, Warsaw, Poland

### **2013**

Birkenbusch, J., Ellermeier, W. & **Kattner, F.** (2013). Octuplicate this interval! In J. Wackermann, M. Wittmann, & W. Skrandies (Eds.), [*Proceedings of the 29th Annual Meeting of the International Society of Psychophysics (Fechner Day 2013)*](http://proceedings.fechnerday.com/index.php/proceedings/article/view/579/569). Freiburg, Germany: International Society for Psychophysics.

**Kattner, F.** (2013). Do concurrent measures of CS valence reveal extinction of evaluative conditioning? Paper presented at the [*13th European Congress of Psychology*](https://europeancongressofpsychology2013.wordpress.com/about/program-overview/). 9-12 July 2013, Stockholm, Sweden.

**Kattner, F.** (2013). Do predictiveness effects on overt attention in contingency learning depend on the valence of the outcome? In U. Ansorge, E. Kirchler, C. Lamm, & H. Leder (Eds.), [*Abstracts of the 55th Conference of Experimental Psychologists*](https://psycharchives.org/bitstream/20.500.12034/679/1/Abstractband_55_2013_wien.pdf) (p. 140). Lengerich: Pabst.

Birkenbusch, J. & **Kattner, F.** (2013). Pre-training performance affects configural discrimination learning. In U. Ansorge, E. Kirchler, C. Lamm, & H. Leder (Eds.), [*Abstracts of the 55th Conference of Experimental Psychologists*](https://psycharchives.org/bitstream/20.500.12034/679/1/Abstractband_55_2013_wien.pdf) (p. 329). Lengerich: Pabst.

**Kattner, F.** & Ellermeier, W. (2013). Magnitude production of pitch ratios: A comparison of musicians and non-musicians. Paper presented at the [*AIA-DAGA 2013 Conference on Acoustics*](https://www.dega-akustik.de/fileadmin/dega-akustik.de/publikationen/DAGA/AIADAGA_13_Program.pdf). Merano, Italy.

### **2012**

**Kattner, F.** & Ellermeier, W. (2012). Can pitch be measured on a ratio scale? In C. Leth-Steensen & J. R. Schoenherr (Eds.), [*Proceedings of the 28th Annual Meeting of the International Society of Psychophysics*](http://proceedings.fechnerday.com/index.php/proceedings/issue/view/1) (pp. 244-249). Ottawa, Canada: Carleton University.

**Kattner, F.** (2012). Does evaluative conditioning occur with negative CS-US contingencies? In A. Bröder, E. Erdfelder, B. E. Hilbig, T. Meiser, R. F. Pohl, & D. Stahlberg (Eds.), *Abstracts of the 54. Tagung experimentell arbeitender Psychologen* (pp. 64-65). Lengerich: Pabst.

Ellermeier, W., **Kattner, F.**, Ueda, K., Doumoto, K., & Nakajima, Y. (2012). Effects of noise-vocoded speech in the irrelevant-sound paradigm. Paper presented at *38. Jahrestagung für Akustik – DAGA 2012* (p. 336). Galrev: Berlin.

### **2011**

Ellermeier, W., **Kattner, F.**, Kurtze, L., Roos, M., Seeber, S., & Bös, J. (2011). Psychophysical scaling of the annoyance produced by photovoltaic inverters. [*Forum Acusticum 2011*](http://www.acta-acustica-united-with-acustica.com/fileadmin/Dateien/Download/ActaAcusticaunitedwithAcustica_TOC_Suppl1_V97.pdf). Aalborg, Denmark.

**Kattner, F.** (2011). Evaluatives Konditionieren mit nicht-detektierten unkonditionierten Reizen: Ein Signalentdeckungs-Experiment. In K. Bittrich, S. Blankenberger, & Lukas, J. (eds.), [*53. Tagung experimentell arbeitender Psychologen*](https://www.psycharchives.org/bitstream/20.500.12034/682/1/Programmheft_TeaP_2011_Halle.pdf) (p. 87). Lengerich: Pabst.

Birkenbusch, J. & **Kattner, F.** (2011). Stimulus properties in contingency learning: The auditory scale illusion produces a negative patterning advantage. In K. Bittrich, S. Blankenberger, & Lukas, J. (eds.), [*53. Tagung experimentell arbeitender Psychologen(https://www.psycharchives.org/bitstream/20.500.12034/682/1/Programmheft_TeaP_2011_Halle.pdf*](https://www.psycharchives.org/bitstream/20.500.12034/682/1/Programmheft_TeaP_2011_Halle.pdf) (p. 209). Lengerich: Pabst.

Ellermeier, W., **Kattner, F.**, Kurtze, L., Roos, M., Seeber, S., & Bös, J. (2011). Psychoakustische Analyse der Betriebsgeräusche von Photovoltaik-Wechselrichtern. Paper presented at *37. Deutsche Jahrestagung für Akustik – DAGA 2011* (p. 171). Berlin: Galrev.

### **2010**

**Kattner, F.** & Ellermeier, W. (2010). Emotional valence and psychoacoustics of irrelevant speech. In A. Bastianelli & G. Vidotto (eds.), [*Proceedings of the 26th Annual Meeting of the International Society of Psychophysics*](http://proceedings.fechnerday.com/index.php/proceedings/article/view/520/511) (pp. 405-408). Padua, Italy.

**Kattner, F.** & Ellermeier, W. (2010). Manipulating contingency awareness in evaluative conditioning via working memory disruption. *Associative Learning Symposium (XIV)*. Gregynog Hall, Wales, UK

**Kattner, F.** & Ellermeier, W. (2010). Die RollederphonologischenSchleifebeimverbalenevaluativenKonditionieren [The role of the phonological loop in verbal evaluative conditioning]. In C. Frings, A. Mecklinger, D. Wentura & H. Zimmer (eds.), [*Beiträge zur 52. Tagung experimentell arbeitender Psychologen*](https://www.psycharchives.org/bitstream/20.500.12034/694/1/Tagungsband_TeaP_2010_SB.pdf) (p. 253). Lengerich: Pabst.

### **2009**

**Kattner, F.** & Ellermeier, W. (2009). The influence of attention and contingency awareness on explicit and implicit measures of evaluative conditioning. *Associative Learning Symposium (XIII)*. Gregynog Hall, Wales, UK.

### **2007**

**Kattner, F.**, Körber, B. & Hammerl, M. (2007). Die ErfassungpupillometrischerDatenbeievaluativerKonditionierung [Pupillary response measurement in evaluative conditioning]. In K. F. Wender, S. Mecklenbrauker, G. D. Rey, T. Wehr (eds.), [*Beiträge zur 49. Tagung experimentell arbeitender Psychologen*](https://psycharchives.org/bitstream/20.500.12034/687/1/Abstractband_TeaP_2007_Trier.pdf) (p. 310). Lengerich: Papst.


## *Book chapters*

Bösche, W. & **Kattner, F.** (2011). Using a violent multiplayer game as a virtual classroom for a course on violent video games. In P. Felicia (ed.), *Handbook of Research on Improving Learning and Motivation through Educational Games: Multidisciplinary Approaches* (pp. 777-805). Hershey, PA: IGI Global.